export enum ActionType {
  ITEM_SELECTED = 'ITEM_SELECTED',
  ITEM_SELECTED_ID = 'ITEM_SELECTED_ID',
  LIKED = 'LIKED',
  RECENTLY_PAGE = 'RECENTLY_PAGE',
  FAVORITED_PAGE = 'FAVORITED_PAGE',
  STYLE_RECENTLY_BTN = 'STYLE_RECENTLY_BTN',
  STYLE_FAVORITED_BTN = 'STYLE_FAVORITED_BTN',
  REMOVE_ITEM = 'REMOVE_ITEM',
  FETCH_DATA = 'FETCH_DATA',
  SET_SELECTED_ITEM = 'SET_SELECTED_ITEM',
}
